spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO_URI}
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
          default-label: main
          search-paths: app-config
logging:
  level:
    org.springframework.cloud.config: DEBUG