spring:
  cloud:
    config:
      server:
        git:
          uri: git@gh_personal:rizkyjayusman/spring-cloud-config.git
          default-label: main
          search-paths: app-config
logging:
  level:
    org.springframework.cloud.config: DEBUG